name: Selenium CI Workflow

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11' # Or '17', ensure this matches your pom.xml and project requirements
          distribution: 'temurin' # Recommended distribution for GitHub Actions
          cache: 'maven' # Cache Maven dependencies

      - name: Build and Test with Maven
        run: mvn -B clean test

      - name: Install Allure CLI
        run: sudo apt-get update && sudo apt-get install -y allure

      - name: Generate Allure HTML report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report-${{ github.run_id }}
          path: allure-report
          retention-days: 7